kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rclone-config
  labels:
    app: rclone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
