kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: rclone
    app.kubernetes.io/part-of: rclone-app
  name: rclone-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
